---
name: Build Docker image and push to ECR

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Needed to interact with GitHub's OIDC Token endpoint
      id-token: write
    steps:
      - name: 'Check out the source code'
        uses: actions/checkout@v3
      - name: 'Configure AWS credential for rcplus-svc (us-east-1)'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::354470900895:role/svc-rcplus-devops-service-role
          role-duration-seconds: 10800 # 3 hours
          role-session-name: PullPublicECR
      - name: 'Login to Amazon Public ECR (us-east-1)'
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public
      - name: 'Configure AWS credential for rcplus-svc (eu-central-1)'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::354470900895:role/svc-rcplus-devops-service-role
          role-duration-seconds: 10800 # 3 hours
          role-session-name: BuildCodeBuildImage
      - name: 'Login to Amazon ECR (eu-central-1)'
        uses: aws-actions/amazon-ecr-login@v1
      - name: 'Create the BuildKit builder'
        run: docker buildx create --bootstrap --name rcplus --driver docker-container --platform linux/amd64,linux/arm64 --use --buildkitd-flags '--allow-insecure-entitlement security.insecure'
      - name: 'Create the emulators'
        run: docker run --privileged --rm public.ecr.aws/eks-distro-build-tooling/binfmt-misc:qemu-v7.0.0 --install arm64,amd64
      - name: 'Build the multi-arch Docker image and push to ECR'
        run: docker buildx build --push --allow security.insecure --platform linux/amd64,linux/arm64 --builder rcplus --tag 354470900895.dkr.ecr.eu-central-1.amazonaws.com/svc-rcplus-devops-codebuild:0.2.0 --tag 354470900895.dkr.ecr.eu-central-1.amazonaws.com/svc-rcplus-devops-codebuild:latest ./app --progress plain
